### PR TITLE
Feature/166 update housingdbapi dependencies

### PR DESCRIPTION
**Pull request by zaclittleberry**

### CODE REVIEW

**Comment by zaclittleberry** [comment]
### Updated all dependencies to latest and ran audit and fixed any issues.

### Removing .then .catch:
If in a handler (function passing request, h), then we should put a value in a
response variable in a try...catch, and return an h.response object. We should 
throw a Boom.badImplementation in the catch.

like so:

let response;
try {
  response = await someFunction(param);
} catch (e) {
  throw Boom.badImplementation('Error during someFunction(param).', e);
}
return h.response(response);


If we're in another function (below the handlers/sometimes exported as a lib),
we shouldn't have a catch. We'll just return the promise and let whatever is
calling to catch the error, that way we don't silence an error by accident.

### Updating route config/options:
switch route.config to route.options


### Start using route.options.pre
added commonly used ensureAdmin and ensureAccount to a helpers.js file to be extracted from regular handlers to pre-handlers (route.options.pre).

**Comment by zaclittleberry** [comment]
I think I messed up all my Boom.badImplementation calls. I used a comma because I was thinking about console.log/error. .badImplementation will take multiple params with data as a second param, but I'm not sure passing the error is proper here. I'll have to look into this.

**Review by VitaRox — COMMENTED** [review]
It all looks good to me, though I had a couple of questions: 
* why change the dependencies to '@hapi/hapi' or '@hapi/boom' instead of just 'boom' or 'hapi'?
* in routes files: why change "config" to "options"?

**Comment by zaclittleberry** [comment]
Hapi and boom packages moved namespaces to be under the @hapi namespace.
See package.json.

Hapi api changed routes config to options in I believe 17. Config still
worked, but I've corrected it to the new naming.

**Comment by zaclittleberry** [comment]
> I think I messed up all my Boom.badImplementation calls. I used a comma because I was thinking about console.log/error. .badImplementation will take multiple params with data as a second param, but I'm not sure passing the error is proper here. I'll have to look into this.

Based on the boom tests, passing the error text as the first param, and the error object as the second is a valid format: https://github.com/hapijs/boom/blob/2aa2cda8e65e68c8db5d263acc3b84eceaba6d3d/test/index.js#L883

**Review by JaniceHe26 — APPROVED** [review]
I like the idea of making the ensure user into a helper function! It really cleans up to code, also I noticed all the functions are now async instead of making the variables async before! This is my first code review, thank you for this opportunity!

**Comment by zaclittleberry** [comment]
Great, thank you both! I'm going to merge this.

**Pull request merged**
